const books = [
	{
		_id: '1',
		title: 'Toward an Old Testament Theology',
		image: '/images/tott.jpg',
		description:
			'Recognizing the major crisis in biblical theology, namely the inability of the discipline to restate and reapply the authority of the Bible, Walter Kaiser here offers a solution to the unresolved issues of definition and methodology in Old Testament theology.',
		author: 'Walter C. Kaiser, Jr.',
		genre: 'Old Testament Theology, Old Testament Bible Study',
		publisher: 'Zondervan',
		publishYear: '1991',
		isbn: '0310371015',
		edition: 'Paperback',
		rating: 4.5,
		numReviews: 24,
	},
	{
		_id: '2',
		title:
			'Biblical Eldership: An Urgent Call to Restore Biblical Church Leadership',
		image: '/images/biblicalEldership.jpg',
		description:
			'With over 200,000 copies sold, this comprehensive look at the role and function of elders brings all the advantages of shared leadership into focus. Beginning with the four broad categories of eldership (leading, feeding, caring, and protecting), Biblical Eldership explores the essential work of elders, their qualifications (including why qualifications are necessary), their relationships with each other, and each of the biblical passages related to eldership. Written for those seeking a clear understanding of the mandate for biblical eldership, this full-length, expository book defines it accurately, practically, and according to Scripture.',
		author: 'Alexander Strauch',
		genre: 'Christian Leadership',
		publisher: 'Lewis and Roth Publishers',
		publishYear: '2003',
		isbn: '0936083115',
		edition: 'Paperback',
		rating: 4.7,
		numReviews: 616,
	},
	{
		_id: '3',
		title: 'The Christ of the Covenants',
		image: '/images/christOfTheCovenants.jpg',
		description:
			'O. Palmer Robertson presents the richness of a covenantal approach to understanding the Bible. He treats the Old Testament covenants from a "successive" standpoint―that each covenant builds on the previous one.',
		author: 'O. Palmer Robertson',
		genre: 'Christology',
		publisher: 'P & R Publishing',
		publishYear: '1987',
		isbn: '9780875524184',
		edition: 'Paperback',
		rating: 4.8,
		numReviews: 249,
	},
	{
		_id: '4',
		title: 'The Christ of the Prophets',
		image: '/images/christOfTheProphets.jpg',
		description:
			'In this thorough introduction to the prophets of ancient Israel, O. Palmer Robertson captures the passion and purpose of their extraordinary writings. He writes, "A new covenant, a new Zion, a new temple, a new messiah, a new relation to the nations of the world-these were the expectations designed to create future hope for the people who would have to endure the trauma of deportation from their land."',
		author: 'O. Palmer Robertson',
		genre: 'Christology',
		publisher: 'P & R Publishing',
		publishYear: '2004',
		isbn: '0875525644',
		edition: 'Paperback',
		rating: 4.23,
		numReviews: 7,
	},
	{
		_id: '5',
		title: 'Toward an Old Testament Ethics',
		image: '/images/tote.jpg',
		description:
			"Biblical ethics is a subject that has been almost totally neglected in this century. Only six men have written a major work on Old Testament ethics in the last hundred years, and only two of these works, both written before 1900, are in English. This lack of materials on Old Testament ethics serves to underscore the significance of Walter Kaiser's Toward Old Testament Ethics. Dr. Kaiser has no illusions about providing a simple solution to questions of Old Testament ethics. ",
		author: 'Walter C. Kaiser, Jr.',
		genre: 'Old Testament Criticism & Interpretation',
		publisher: 'Zondervan Academic',
		publishYear: '1991',
		isbn: '0310371112',
		edition: 'Paperback',
		rating: 4.7,
		numReviews: 17,
	},
	{
		_id: '6',
		title: 'The Pentateuch as Narrative',
		image: '/images/pentateuchNarrative.jpg',
		description:
			'The Pentateuch as Narrative focuses on the narrative and literary continuity of the Pentateuch as a whole rather than individual books. It seeks to disclose how the original Jewish readers may have viewed this multivolume work of Moses. Its central thesis is that the Pentateuch was written from the perspective of one who had lived under the Law of the Covenant established at Mount Sinai and had seen its failure to produce genuine trust in the Lord God of Israel. In this context, the Pentateuch pointed the reader forward to the hope of the New Covenant, based on divine faithfulness.',
		author: 'John H. Sailhamer',
		genre: 'Christian Historical Theology (Books)',
		publisher: 'Zondervan Academic',
		publishYear: '1995',
		isbn: '9780310574217',
		edition: 'Paperback',
		rating: 4.7,
		numReviews: 220,
	},
];

export default books;
